name: Build and Install Qt on ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ARM64 environment
      uses: uraimo/run-on-arch-action@v2.3.1
      with:
        architecture: arm64
        distro: ubuntu20.04

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgl1-mesa-dev libxcb-xinerama0-dev libfontconfig1-dev \
          libxkbcommon-x11-dev libxi-dev libxrender-dev libxrandr-dev libxcursor-dev libx11-xcb-dev \
          libglu1-mesa-dev ninja-build wget

    - name: Install Qt 6.5.3
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'

    - name: Set up environment variables
      run: |
        echo "export PATH=$HOME/Qt/6.5.3/gcc_64/bin:\$PATH" >> $GITHUB_ENV
        echo "export LD_LIBRARY_PATH=$HOME/Qt/6.5.3/gcc_64/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "export PKG_CONFIG_PATH=$HOME/Qt/6.5.3/gcc_64/lib/pkgconfig:\$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Verify installation
      run: |
        source $GITHUB_ENV
        qmake --version
